name: Build
on:
  push:
    branches:
      - master
      - branch-*
      - code-smells
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: JaCoCo Report
        uses: Madrapps/jacoco-report@v1.2
        with:
          # Comma separated paths of the generated jacoco xml files
          paths: target/site/jacoco/jacoco.xml
          # Github personal token to add commits to Pull Request
          token: ${{ secrets.GITHUB_TOKEN }}
          # The minimum code coverage that is required to pass for overall project
          min-coverage-overall: 70 # optional, default is 80
          # The minimum code coverage that is required to pass for changed files
          min-coverage-changed-files: 70 # optional, default is 80
          # Optional title for the Pull Request comment
          title: code-report # optional
          # Run the action in debug mode and get debug logs printed in console
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=KonsInator_ThePlains
